---
extends: default
rules:
  indentation:
    spaces: 2
    indent-sequences: false
  line-length:
    max: 160
    allow-non-breakable-words: true
  trailing-spaces: enable
  comments:
    min-spaces-from-content: 1
  empty-lines:
    max: 1
    max-start: 0
    max-end: 1
