---
  - name: Create temporary directory to save the script
    tempfile:
      prefix: odoo-module-scripts
      state: directory
    register: temp_dir

  - name: Copy Uninstall Odoo modules Script
    template:
      src: uninstall_modules.py.j2
      dest: "{{ temp_dir.path }}/{{ uninstall_modules_script_dest }}"
      owner: '{{ tablet_user }}'
      group: '{{ tablet_user }}'
      mode: 0733
    tags: ['uninstall']

  - name: check if script file exist
    stat:
      path: "{{ temp_dir.path }}/{{ uninstall_modules_script_dest }}"
    register: stat_result
    tags: ['uninstall']

  - name: Uninstall Odoo modules using generated script
    command: "python {{ temp_dir.path }}/{{ uninstall_modules_script_dest }}"
    when: stat_result.stat.exists == True
    tags: ['uninstall']

  - name: delete temporary files
    file:
      state: absent
      path: "{{ temp_dir.path }}"
