---
  - name: Create temporary directory to save the script
    tempfile:
      prefix: odoo-module-scripts
      state: directory
    register: temp_dir

  - name: Copy Update Odoo modules List Script
    template:
      src: update_list.py.j2
      dest: "{{ temp_dir.path }}/{{ update_list_script_dest }}"
      owner: '{{ tablet_user }}'
      group: '{{ tablet_user }}'
      mode: 0733

  - name: check if script file exist
    stat:
      path: "{{ temp_dir.path }}/{{ update_list_script_dest }}"
    register: stat_result

  # ✅ Convertir automatiquement le script Python 2 -> Python 3
  - name: Convert script to Python 3 (2to3)
    ansible.builtin.command:
      cmd: "python3 -m lib2to3 -w {{ tempdir.path }}/update_list.py"
    changed_when: false

  # ✅ Lancer explicitement avec python3
  - name: Update Odoo modules list using generated script
    ansible.builtin.command:
      cmd: "python3 {{ tempdir.path }}/update_list.py"

  # - name: Update Odoo modules list using generated script
  #   command: "python {{ temp_dir.path }}/{{ update_list_script_dest }}"
  #   when: stat_result.stat.exists == True

  - name: delete temporary files
    file:
      state: absent
      path: "{{ temp_dir.path }}"
