---
- name: Create temporary directory to save the script
  ansible.builtin.tempfile:
    prefix: odoo-module-scripts
    state: directory
  register: temp_dir

- name: Render Update Odoo modules list script
  ansible.builtin.template:
    src: update_list.py.j2
    dest: "{{ temp_dir.path }}/{{ update_list_script_dest }}"
    owner: "{{ tablet_user }}"
    group: "{{ tablet_user }}"
    mode: "0755"              # exécutable, en chaîne (évite l'octal implicite)

- name: Check if script file exists
  ansible.builtin.stat:
    path: "{{ temp_dir.path }}/{{ update_list_script_dest }}"
  register: stat_result

# - name: Wait until Odoo HTTP API is reachable
#   ansible.builtin.wait_for:
#     host: "{{ odoo_host | default('odoo') }}"
#     port: "{{ odoo_port | default(8069) }}"
#     connect_timeout: 2
#     delay: 1
#     timeout: 900

# Convertir automatiquement le script Python 2 -> Python 3, si présent
- name: Convert script to Python 3 (lib2to3)
  ansible.builtin.shell: |
    set -o pipefail
    python3 -m lib2to3 -w "{{ temp_dir.path }}/{{ update_list_script_dest }}"
  args:
    executable: /bin/bash
  changed_when: false
  when: stat_result.stat.exists

# Lancer explicitement avec python3
- name: Update Odoo modules list using generated script
  ansible.builtin.command:
    cmd: "python3 {{ temp_dir.path }}/{{ update_list_script_dest }}"
  when: stat_result.stat.exists

- name: Delete temporary files
  ansible.builtin.file:
    state: absent
    path: "{{ temp_dir.path }}"
