---
- name: Converge
  hosts: instance
  gather_facts: true

  pre_tasks:
    - name: Ensure 'pi' user exists
      become: true
      ansible.builtin.user:
        name: pi
        state: present

  tasks:
    - name: Ensure Python 3 is present (bootstrap)
      become: true
      ansible.builtin.raw: |
        test -e /usr/bin/python3 || (apt-get update -y && apt-get install -y python3)

    - name: Show container status (runner)
      ansible.builtin.command: docker ps -a
      delegate_to: localhost
      register: docker_ps
      changed_when: false

    - name: Debug docker ps
      ansible.builtin.debug:
        var: docker_ps.stdout_lines

    # Attendre Postgres côté runner (port publié)
    - name: Wait until Postgres (runner) listens on 5432
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 5432
        timeout: 300
        state: started
      delegate_to: localhost
      changed_when: false

    # S'assurer que le one-shot est fini (échappement des {{ }})
    - name: Wait until odoo_init finished successfully (or exited)
      ansible.builtin.command: >
        docker inspect -f '{{"{{"}}.State.Status{{"}}"}} {{"{{"}}.State.ExitCode{{"}}"}}' odoo_init
      delegate_to: localhost
      register: odoo_init_state
      until: >
        ('exited 0' in odoo_init_state.stdout) or
        ('exited 137' in odoo_init_state.stdout) or
        ('running' in odoo_init_state.stdout)
      retries: 180
      delay: 2
      changed_when: false

    # Attendre Odoo côté runner
    - name: Wait until Odoo answers on 8069 (runner)
      ansible.builtin.wait_for:
        host: 127.0.0.1
        port: 8069
        timeout: 900
        state: started
      delegate_to: localhost
      changed_when: false

    # Attendre Odoo depuis 'instance' vers le service 'odoo'
    - name: Wait until Odoo answers on 8069 (from instance)
      ansible.builtin.wait_for:
        host: odoo
        port: 8069
        timeout: 900
        state: started
      changed_when: false

    # Ping HTTP pour confirmer que le webclient répond
    - name: Wait Odoo HTTP /web/webclient/version_info returns 200
      ansible.builtin.uri:
        url: http://odoo:8069/web/webclient/version_info
        method: GET
        status_code: 200
      register: odoo_http
      until: odoo_http.status == 200
      retries: 90
      delay: 5
      changed_when: false

  roles:
    - role: diranetafen.odoo_module
      vars:
        odoo_host: "odoo"
        odoo_port: 8069
        odoo_database_name: testdb
        odoo_admin_login: admin
        odoo_admin_password: admin
