---
- name: Converge
  hosts: instance
  gather_facts: true

  tasks:
    - name: Ensure Python 3 is present (bootstrap)
      become: true
      raw: |
        test -e /usr/bin/python3 || (apt-get update -y && apt-get install -y python3)

    - name: Ensure 'pi' user exists (only on instance)
      become: true
      user:
        name: pi
        state: present

    - name: Show container status
      command: docker ps -a
      delegate_to: localhost
      register: docker_ps
      changed_when: false

    - debug:
        var: docker_ps.stdout_lines

    - name: Wait until Postgres logs say 'ready to accept connections'
      shell: |
        docker logs db 2>&1 | tail -n 200 | grep -q "database system is ready to accept connections"
      args:
        executable: /bin/bash
      delegate_to: localhost
      register: pg_ready
      until: pg_ready.rc == 0
      retries: 180
      delay: 2
      changed_when: false

    - name: Wait until Odoo answers on 8069
      wait_for:
        host: 127.0.0.1
        port: 8069
        timeout: 900
        state: started
      delegate_to: localhost
      changed_when: false

  roles:
    - role: diranetafen.odoo_module
      vars:
        odoo_host: "odoo"
        odoo_port: 8069
        odoo_database_name: testdb
        odoo_admin_login: admin
        odoo_admin_password: admin
