---
- name: Converge
  hosts: all
  gather_facts: false
  become: false

  pre_tasks:
    - name: Ensure Python 3 is present (bootstrap)
      ansible.builtin.raw: |
        test -e /usr/bin/python3 || \
        ( (command -v apt-get >/dev/null && apt-get update -y && apt-get install -y python3) || \
          (command -v dnf >/dev/null && dnf install -y python3) || \
          (command -v yum >/dev/null && yum install -y python3) )
      changed_when: false

    - name: Ensure 'pi' user exists
      ansible.builtin.user:
        name: pi
        shell: /bin/bash
        create_home: true

      - name: Ensure 'python' shim points to python3
        ansible.builtin.raw: |
          command -v python >/dev/null && exit 0
          if command -v apt-get >/dev/null; then
            apt-get update -y && apt-get install -y python-is-python3 || ln -sf /usr/bin/python3 /usr/bin/python
          elif command -v dnf >/dev/null || command -v yum >/dev/null; then
            (command -v dnf && dnf install -y python3) || (command -v yum && yum install -y python3)
            (command -v alternatives && alternatives --install /usr/bin/python python /usr/bin/python3 1) || ln -sf /usr/bin/python3 /usr/bin/python
          else
            ln -sf /usr/bin/python3 /usr/bin/python
          fi
        changed_when: false

    - name: Gather facts (after python available)
      ansible.builtin.setup:

  roles:
    - role: diranetafen.odoo_module
      vars:
        # ➜ REMPLIS ICI les variables minimales requises par le rôle
        #   (ex: odoo_module_name, addons_path, repo, version, etc.)
        #   selon le README du rôle.
        odoo_module_name: demo_module
        odoo_addons_path: /opt/odoo/custom_addons
