---
- name: Converge
  hosts: instance
  gather_facts: true

  pre_tasks:
    - name: Ensure 'pi' user exists
      become: true
      user:
        name: pi
        state: present

    - name: Show container status (runner)
      command: docker ps -a
      delegate_to: localhost
      register: docker_ps
      changed_when: false

    - debug:
        var: docker_ps.stdout_lines

    - name: Wait until Postgres logs say 'ready to accept connections' (runner)
      shell: |
        docker logs db 2>&1 | grep -q "database system is ready to accept connections"
      args:
        executable: /bin/bash
      delegate_to: localhost
      register: pg_ready
      until: pg_ready.rc == 0
      retries: 180
      delay: 2
      changed_when: false

    - name: Wait until odoo_init finished successfully (runner)
      command: docker inspect -f '{{.State.Status}} {{.State.ExitCode}}' odoo_init
      delegate_to: localhost
      register: odoo_init_state
      retries: 180
      delay: 2
      until: >
        ('exited 0' in odoo_init_state.stdout) or
        ('running' in odoo_init_state.stdout)
      changed_when: false

    - name: Wait until Odoo answers on 8069 (runner → port publié)
      wait_for:
        host: 127.0.0.1
        port: 8069
        timeout: 900
        state: started
      delegate_to: localhost
      changed_when: false

    - name: Wait until Odoo answers on 8069 from instance (réseau molnet)
      wait_for:
        host: odoo
        port: 8069
        timeout: 900
        state: started
      changed_when: false

    - name: Wait Odoo HTTP /web/webclient/version_info returns 200
      uri:
        url: http://odoo:8069/web/webclient/version_info
        method: GET
        status_code: 200
      register: odoo_http
      retries: 90
      delay: 5
      until: odoo_http.status == 200
      changed_when: false

  roles:
    - role: diranetafen.odoo_module
      vars:
        odoo_host: "odoo"
        odoo_port: 8069
        odoo_database_name: testdb
        odoo_admin_login: admin
        odoo_admin_password: admin
