---
- name: Converge
  hosts: all
  gather_facts: false
  become: false

  pre_tasks:
    - name: Ensure Python 3 is present (bootstrap)
      ansible.builtin.raw: |
        test -e /usr/bin/python3 || \
        ( (command -v apt-get >/dev/null && apt-get update -y && apt-get install -y python3) || \
          (command -v dnf >/dev/null && dnf install -y python3) || \
          (command -v yum >/dev/null && yum install -y python3) )
      changed_when: false

    - name: Ensure 'pi' user exists
      ansible.builtin.user:
        name: pi
        shell: /bin/bash
        create_home: true

    # Dans pre_tasks de converge.yml (Ubuntu/Debian)
    - name: Install python2 (if available) and point python -> python2
      ansible.builtin.raw: |
        (command -v apt-get && apt-get update -y && apt-get install -y python2) || true
        if command -v python2 >/dev/null; then ln -sf "$(command -v python2)" /usr/bin/python; fi
      changed_when: false

    - name: Gather facts (after python available)
      ansible.builtin.setup:

  roles:
    - role: diranetafen.odoo_module
      vars:
        # ➜ REMPLIS ICI les variables minimales requises par le rôle
        #   (ex: odoo_module_name, addons_path, repo, version, etc.)
        #   selon le README du rôle.
        odoo_module_name: demo_module
        odoo_addons_path: /opt/odoo/custom_addons
