- hosts: instance
  gather_facts: false

  pre_tasks:
- name: Show container status
  command: docker ps -a
  delegate_to: localhost
  register: docker_ps
  changed_when: false

- debug:
    var: docker_ps.stdout_lines

    
    - name: Wait until Postgres logs say "ready to accept connections"
      delegate_to: localhost
      run_once: true
      retries: 120
      delay: 5
      changed_when: false
      shell: |
        docker logs db 2>&1 | tail -n 400 | grep -q "database system is ready to accept connections"
    
    - name: Show last Odoo logs (for debug if needed)
      delegate_to: localhost
      run_once: true
      changed_when: false
      shell: docker logs --tail=200 odoo || true

    - name: Wait until Odoo HTTP is reachable
      wait_for:
        host: "{{ odoo_host | default('odoo') }}"
        port: "{{ odoo_port | default(8069) }}"
        connect_timeout: 2
        delay: 1
        timeout: 900

  roles:
    - role: diranetafen.odoo_module
      vars:
        odoo_host: "odoo"
        odoo_port: 8069
        odoo_database_name: testdb
        odoo_admin_login: admin
        odoo_admin_password: admin
