---
- name: Converge
  hosts: instance
  gather_facts: false
  become: false

  vars:
    pg_ready_timeout: 600   # 10 min max pour initdb la première fois
    odoo_ready_timeout: 420

  pre_tasks:
    - name: Ensure Python 3 is present (bootstrap)
      ansible.builtin.raw: |
        test -e /usr/bin/python3 || \
        ( (command -v apt-get >/dev/null && apt-get update -y && apt-get install -y python3) || \
          (command -v dnf >/dev/null && dnf install -y python3) || \
          (command -v yum >/dev/null && yum install -y python3) )
      changed_when: false

    - name: Ensure 'pi' user exists (only on instance)
      ansible.builtin.user:
        name: pi
        shell: /bin/bash
        create_home: true

    - name: Ensure 'python' shim points to python3 (only on instance)
      ansible.builtin.raw: |
        command -v python >/dev/null && exit 0
        if command -v apt-get >/dev/null; then
          apt-get update -y && apt-get install -y python-is-python3 || ln -sf /usr/bin/python3 /usr/bin/python
        elif command -v dnf >/dev/null || command -v yum >/dev/null; then
          (command -v dnf && dnf install -y python3) || (command -v yum && yum install -y python3)
          (command -v alternatives && alternatives --install /usr/bin/python python /usr/bin/python3 1) || ln -sf /usr/bin/python3 /usr/bin/python
        else
          ln -sf /usr/bin/python3 /usr/bin/python
        fi
      changed_when: false

    - name: Gather facts (after python available)
      ansible.builtin.setup:

    - name: Check name resolution for db and odoo (depuis l'hôte Ansible)
      ansible.builtin.shell: getent hosts {{ item }}
      register: dns_out
      changed_when: false
      loop: [ "db", "odoo" ]

    - name: Ensure DB container is running
      ansible.builtin.shell: docker inspect -f '{{ "{{.State.Status}}" }}' db
      register: db_state
      changed_when: false
      retries: 60
      delay: 5
      until: db_state.stdout.strip() == "running"
      delegate_to: localhost
      run_once: true

    - name: Get DB container IP
      ansible.builtin.shell: >
        docker inspect -f '{{ "{% raw %}{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}{% endraw %}" }}' db
      register: db_ip_out
      changed_when: false
      delegate_to: localhost
      run_once: true

    - name: Set fact db_host
      ansible.builtin.set_fact:
        db_host: "{{ db_ip_out.stdout | trim | default('db') }}"

    - name: Wait TCP 5432 (DB by IP)
      ansible.builtin.wait_for:
        host: "{{ db_host }}"
        port: 5432
        delay: 3
        timeout: 900   # 15 min pour laisser initdb finir

    - name: Confirm Postgres answers (pg_isready in container)
      ansible.builtin.shell: docker exec db pg_isready -h 127.0.0.1 -p 5432 -U postgres
      register: pgready
      changed_when: false
      retries: 60
      delay: 5
      until: pgready.rc == 0
      delegate_to: localhost
      run_once: true

    # ---------- Odoo init + service ----------
    - name: Wait for odoo_init to finish successfully (one-shot container)
      ansible.builtin.shell: docker inspect -f '{{ "{{.State.Status}} {{.State.ExitCode}}" }}' odoo_init
      register: odoo_init_state
      changed_when: false
      retries: 90
      delay: 5
      until: "'exited 0' in odoo_init_state.stdout"
      delegate_to: localhost
      run_once: true

    - name: Ensure Odoo service container is running
      ansible.builtin.shell: docker inspect -f '{{ "{{.State.Status}}" }}' odoo
      register: odoo_state
      changed_when: false
      retries: 60
      delay: 5
      until: odoo_state.stdout.strip() == "running"
      delegate_to: localhost
      run_once: true

    # ---------- IPs réelles des conteneurs ----------
    - name: Get container IPs (db, odoo)
      ansible.builtin.shell: >
        docker inspect -f '{{ "{% raw %}{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}{% endraw %}" }}' {{ item }}
      register: ip_out
      changed_when: false
      loop: [ "db", "odoo" ]
      delegate_to: localhost
      run_once: true

    - name: Set facts with real container IPs
      ansible.builtin.set_fact:
        db_host: "{{ (ip_out.results | selectattr('item','equalto','db')   | first).stdout | trim | default('db') }}"
        odoo_host: "{{ (ip_out.results | selectattr('item','equalto','odoo') | first).stdout | trim | default('odoo') }}"

    - name: Wait TCP 8069 (by IP)
      ansible.builtin.wait_for:
        host: "{{ odoo_host }}"
        port: 8069
        delay: 5
        timeout: "{{ odoo_ready_timeout }}"

    - name: Wait for Odoo web login to answer 200
      ansible.builtin.uri:
        url: "http://{{ odoo_host }}:8069/web/login"
        status_code: 200
        return_content: false
      register: odoo_http
      retries: 30
      delay: 5
      until: odoo_http.status == 200

  roles:
    - role: diranetafen.odoo_module
      vars:
        # on injecte l'IP résolue par Docker
        odoo_host: "{{ odoo_host }}"
        odoo_url: "http://{{ odoo_host }}:8069"
        odoo_port: 8069
        odoo_admin_login: "admin"
        odoo_admin_password: "admin"
        odoo_database_name: "testdb"
        modules_to_install: []
        modules_to_upgrade: []
        modules_to_uninstall: []
        odoo_timeout: 240   # évite le warning sur le nom réservé 'timeout'