dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: "${MOLECULE_EPHEMERAL_DIRECTORY}/roles"
    force: true

driver:
  name: docker
platforms:
  # Réseau commun pour activer la résolution DNS par nom
  # (Molecule créera/supprimera ce réseau)
  - name: db
    image: postgres:15-alpine
    pre_build_image: true
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: testdb
    networks:
      - name: molnet

  - name: odoo
    image: odoo:16
    pre_build_image: true
    environment:
      DB_HOST: db
      DB_USER: odoo
      DB_PASSWORD: odoo
    # Pas de $ ni de $(...) -> on évite l'interpolation Molecule
    command: >
      sh -lc "
        python3 - <<'PY'
import socket, time, sys
for _ in range(120):
    try:
        s = socket.create_connection(('db', 5432), 2)
        s.close()
        break
    except Exception:
        time.sleep(2)
else:
    sys.exit('db not ready')
PY
        ; odoo -d testdb --db_host=db --db_user=odoo --db_password=odoo --without-demo=all -i base --stop-after-init
        ; exec odoo -d testdb --db_host=db --db_user=odoo --db_password=odoo --without-demo=all
      "
    published_ports:
      - "8069:8069"
    networks:
      - name: molnet

  - name: instance
    image: ${MOLECULE_IMAGE:-geerlingguy/docker-ubuntu2204-ansible}
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    # Lien legacy (file /etc/hosts) au cas où le réseau ne serait pas créé
    links:
      - "odoo:odoo"
      - "db:db"
    networks:
      - name: molnet


provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  config_options:
    defaults:
      host_key_checking: false

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy