dependency:
  name: galaxy
  options:
    role-file: requirements.yml
    roles-path: "${MOLECULE_EPHEMERAL_DIRECTORY}/roles"
    force: true

driver:
  name: docker

platforms:
  - name: db
    image: postgres:15
    pre_build_image: true
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: testdb
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C.UTF-8"
    command: ["postgres", "-c", "listen_addresses=*"]
    published_ports:
      - "5432:5432"
    networks:
      - name: molnet

  # ---- One-shot: attend santé Postgres puis initialise la DB Odoo ----
  - name: odoo_init
    image: odoo:16
    pre_build_image: true
    environment:
      DB_HOST: db
      DB_USER: odoo
      DB_PASSWORD: odoo
    entrypoint: ["/bin/sh", "-lc"]
    command: |
      python3 - <<'PY'
      import socket, time, sys
      # attendre Postgres sur 'db:5432'
      for _ in range(180):
          try:
              s = socket.create_connection(('db', 5432), 2)
              s.close()
              break
          except Exception:
              time.sleep(2)
      else:
          sys.exit('db not ready')
      PY
      # initialiser la base
      odoo -d testdb --db_host=db --db_user=odoo --db_password=odoo --without-demo=all -i base --stop-after-init
    networks:
      - name: molnet

  # ---- Service Odoo (ENTRYPOINT par défaut) ----
  - name: odoo
    image: odoo:16
    pre_build_image: true
    environment:
      DB_HOST: db
      DB_USER: odoo
      DB_PASSWORD: odoo
    command: >
      --database testdb
      --db_host db --db_user odoo --db_password odoo
      --without-demo=all
      --http-interface 0.0.0.0 --http-port 8069
    published_ports:
      - "8069:8069"
    networks:
      - name: molnet

  # ---- Hôte Ansible ----
  - name: instance
    image: ${MOLECULE_IMAGE:-geerlingguy/docker-ubuntu2204-ansible}
    command: /sbin/init
    privileged: true
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
      - /tmp
    networks:
      - name: molnet

provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
  config_options:
    defaults:
      host_key_checking: false

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - side_effect
    - verify
    - cleanup
    - destroy
