---
dependency:
  name: galaxy
  options:
    ignore-errors: true
    force: true
driver:
  name: docker
platforms:
  - name: ubuntu-20.04
    image: ubuntu:20.04
    pre_build_image: true
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    environment:
      container: docker
    networks:
      - name: molecule-network
  - name: ubuntu-22.04
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    cgroupns_mode: host
    command: "/lib/systemd/systemd"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    environment:
      container: docker
    networks:
      - name: molecule-network
  - name: centos-8
    image: quay.io/centos/centos:stream8
    pre_build_image: true
    privileged: true
    volume_mounts:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    cgroupns_mode: host
    command: "/usr/sbin/init"
    tmpfs:
      - /run
      - /tmp
    capabilities:
      - SYS_ADMIN
    environment:
      container: docker
    networks:
      - name: molecule-network

provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
      stdout_callback: yaml
    ssh_connection:
      pipelining: false
  inventory:
    host_vars:
      ubuntu-20.04:
        odoo_version: "14.0"
        odoo_user: "odoo"
        odoo_db_host: "localhost"
        odoo_db_port: 5432
        odoo_db_user: "odoo"
        odoo_db_password: "odoo"
        modules_to_install:
          - "sale_management"
          - "purchase"
        action: "install"
      ubuntu-22.04:
        odoo_version: "15.0"
        odoo_user: "odoo"
        odoo_db_host: "localhost"
        odoo_db_port: 5432
        odoo_db_user: "odoo"
        odoo_db_password: "odoo"
        modules_to_upgrade:
          - "stock"
        action: "upgrade"
      centos-8:
        odoo_version: "16.0"
        odoo_user: "odoo"
        odoo_db_host: "localhost"
        odoo_db_port: 5432
        odoo_db_user: "odoo"
        odoo_db_password: "odoo"
        action: "update_list"

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
  create_sequence:
    - dependency
    - create
    - prepare
  converge_sequence:
    - dependency
    - create
    - prepare
    - converge
  destroy_sequence:
    - dependency
    - cleanup
    - destroy
  check_sequence:
    - dependency
    - cleanup
    - destroy
    - create
    - prepare
    - converge
    - check
    - destroy