name: Molecule Multi-OS Test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  molecule:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - label: ubuntu2204
            image: geerlingguy/docker-ubuntu2204-ansible
          - label: debian12
            image: geerlingguy/docker-debian12-ansible
          - label: rockylinux8
            image: geerlingguy/docker-rockylinux8-ansible

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install toolchain
        run: |
          python -m pip install --upgrade pip
          pip install molecule "molecule-plugins[docker]" ansible ansible-lint testinfra docker

      - name: Install collections
        run: ansible-galaxy collection install -r collections/requirements.yml

      # - name: Lint role
      #   run: ansible-lint

      - name: Run Molecule ${{ matrix.label }}
        env:
          MOLECULE_IMAGE: ${{ matrix.image }}
        run: molecule test

